# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: /content/skeleton-based-action-recognition/data_coup/x_test.npy
  label_path: /content/skeleton-based-action-recognition/data_coup/test_label.pkl
  debug: False

# model
model: model.stgcn.STGCN
model_args:
  num_class: 2
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'


# test 
phase: test
device: [0]
test_batch_size: 256
weights: ./runs/stbln/ntu_cv_stgcn_joint-49-2350.pt

work_dir: ./work_dir/ntu/xview/agcn_test_joint
model_saved_name: ./runs/ntu_cv_agcn_test_joint
save_score: True
