work_dir: ./work_dir/ntu/xview/stgcn_joint
model_saved_name: ./runs/stbln/ntu_cv_stgcn_joint
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: /content/skeleton-based-action-recognition/data_coup/x_train.npy
  label_path: /content/skeleton-based-action-recognition/data_coup/train_label.pkl
  
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: /content/skeleton-based-action-recognition/data_coup/x_test.npy
  label_path: /content/skeleton-based-action-recognition/data_coup/test_label.pkl

# model
model: model.stgcn.STGCN
model_args:
  num_class: 2
  num_point: 15
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [30, 40]

# training
device: [0]
batch_size: 64
test_batch_size: 128
num_epoch: 50
nesterov: True
